const cardData = [
  {
    id: 1,
    title: "Riding the Space Coast",
    description:
      "Explore the Space Coast's history and enjoy some of the best fishing around Florida's incredible coast.",
    image: "https://via.placeholder.com/600x400",
    date: "07.22.2019",
    buttonText: "Read More",
    style: "bg-[#F1F1EF] text-black text-center",
    href: "http://google.com/",
  },
  {
    id: 2,
    title: "Nolan & Co",
    description:
      "A digital product agency that focuses on strategy and design.",
    image: "https://via.placeholder.com/600x400",
    date: "",
    buttonText: "Read More",
    style: "bg-[#F1F1EF] text-black text-center",
    href: "http://github.com/",
  },
  {
    id: 3,
    title: "Utica",
    description: "Utica is an architecture firm based in Copenhagen, Denmark.",
    image: "https://via.placeholder.com/600x400",
    date: "",
    buttonText: "Explore",
    style: "bg-[#F1F1EF] text-black text-center",
    href: "http://x.com/",
  },
  {
    id: 4,
    title: "Riding the Space Coast",
    description:
      "Explore the Space Coast's history and enjoy some of the best fishing around Florida's incredible coast.",
    image: "https://via.placeholder.com/600x400",
    date: "07.22.2019",
    buttonText: "Read More",
    style: "bg-[#F1F1EF] text-black text-center",
    href: "http://bing.com/",
  },
  {
    id: 5,
    title: "Nolan & Co",
    description:
      "A digital product agency that focuses on strategy and design.",
    image: "https://via.placeholder.com/600x400",
    date: "",
    buttonText: "Read More",
    style: "bg-[#F1F1EF] text-black text-center",
    href: "http://yahoo.com/",
  },
  {
    id: 6,
    title: "Utica",
    description: "Utica is an architecture firm based in Copenhagen, Denmark.",
    image: "https://via.placeholder.com/300x200",
    date: "",
    buttonText: "Explore",
    style: "bg-[#F1F1EF] text-black text-center",
    href: "http://hotmail.com/",
  },
  {
    id: 7,
    title: "Utica",
    description: "Utica is an architecture firm based in Copenhagen, Denmark.",
    image: "https://via.placeholder.com/300x200",
    date: "",
    buttonText: "Explore",
    style: "bg-[#F1F1EF] text-black text-center",
    href: "http://netflix.com/",
  },
  {
    id: 8,
    title: "Utica",
    description: "Utica is an architecture firm based in Copenhagen, Denmark.",
    image: "https://via.placeholder.com/300x200",
    date: "",
    buttonText: "Explore",
    style: "bg-[#F1F1EF] text-black text-center",
    href: "http://tesla.com/",
  },
  {
    id: 9,
    title: "Utica",
    description: "Utica is an architecture firm based in Copenhagen, Denmark.",
    image: "https://via.placeholder.com/300x200",
    date: "",
    buttonText: "Explore",
    style: "bg-[#F1F1EF] text-black text-center",
    href: "http://taco.com/",
  },
];

export default cardData;
